/*
 * Client-side site search.
 *
 * Webflow's search is a server-side feature of Webflow hosting and was lost in
 * the export, leaving /search as a form with nowhere to post. This queries
 * search-index.json (generated by tools/build-search-index.mjs) in the browser
 * instead, so search works on any static host.
 */
(function () {
  'use strict'

  var INDEX_URL = '/search-index.json'
  var MAX_RESULTS = 20
  var SNIPPET_BEFORE = 70
  var SNIPPET_AFTER = 190

  var form = document.querySelector('.search-form')
  var input = form && form.querySelector('input[type="search"], input[name="query"]')
  var resultsEl = document.querySelector('[data-search-results]')
  if (!form || !input || !resultsEl) return

  var statusEl = document.querySelector('[data-search-status]')
  var indexPromise = null

  // --- text handling ---------------------------------------------------

  var COMBINING = /[̀-ͯ]/g
  var APOSTROPHES = /['‘’ʼ]/g
  var canNormalize = typeof ''.normalize === 'function'

  function normalize(s) {
    var out = s.toLowerCase()
    // Strip diacritics so "cafes" matches "cafés". Guarded because normalize()
    // is absent on some older mobile browsers.
    if (canNormalize) out = out.normalize('NFD').replace(COMBINING, '')
    // Curly apostrophes are collapsed rather than spaced so "customer's"
    // normalizes to one token, not two.
    return out.replace(APOSTROPHES, '').replace(/[^a-z0-9]+/g, ' ').trim()
  }

  // Case- and accent-folded, but one output character per input character, so
  // an index found here still points at the right spot in the original string.
  function foldAligned(s) {
    var out = ''
    for (var i = 0; i < s.length; i++) {
      var ch = s.charAt(i).toLowerCase()
      if (canNormalize) {
        var stripped = ch.normalize('NFD').replace(COMBINING, '')
        if (stripped.length === 1) ch = stripped
      }
      out += ch
    }
    return out
  }

  function terms(query) {
    var seen = {}
    var out = []
    var parts = normalize(query).split(' ')
    for (var i = 0; i < parts.length; i++) {
      var t = parts[i]
      if (!t || seen[t]) continue
      seen[t] = true
      out.push(t)
    }
    return out
  }

  function escapeRe(s) {
    return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  }

  function countOccurrences(haystack, term) {
    var re = new RegExp(escapeRe(term), 'g')
    var n = 0
    while (re.exec(haystack) !== null) {
      n++
      if (n >= 20) break
    }
    return n
  }

  // --- scoring ---------------------------------------------------------

  function prepare(data) {
    var pages = (data && data.pages) || []
    return pages.map(function (p) {
      return {
        url: p.url,
        title: p.title || p.url,
        description: p.description || '',
        text: p.text || '',
        nTitle: ' ' + normalize(p.title || '') + ' ',
        nHeadings: ' ' + normalize((p.headings || []).join(' ')) + ' ',
        nDescription: ' ' + normalize(p.description || '') + ' ',
        nText: ' ' + normalize(p.text || '') + ' ',
      }
    })
  }

  function scorePage(page, queryTerms) {
    var score = 0
    var matched = 0

    for (var i = 0; i < queryTerms.length; i++) {
      var term = queryTerms[i]
      var termScore = 0

      // A whole-word title hit is the strongest signal there is: it's how
      // "pricing" or "hotels" reaches the page actually named that.
      if (page.nTitle.indexOf(' ' + term + ' ') !== -1) termScore += 16
      else if (page.nTitle.indexOf(term) !== -1) termScore += 9

      if (page.nHeadings.indexOf(term) !== -1) termScore += 6
      if (page.nDescription.indexOf(term) !== -1) termScore += 4

      var hits = countOccurrences(page.nText, term)
      if (hits) termScore += Math.min(hits, 5) * 1.5

      if (termScore) matched++
      score += termScore
    }

    if (!matched) return 0
    // A page containing every term should always outrank one that happens to
    // repeat a single term many times.
    if (matched === queryTerms.length && queryTerms.length > 1) score += 15
    return score
  }

  function search(pages, query) {
    var queryTerms = terms(query)
    if (!queryTerms.length) return []

    var hits = []
    for (var i = 0; i < pages.length; i++) {
      var score = scorePage(pages[i], queryTerms)
      if (score > 0) hits.push({ page: pages[i], score: score })
    }

    hits.sort(function (a, b) {
      if (b.score !== a.score) return b.score - a.score
      return a.page.title.localeCompare(b.page.title)
    })
    return hits.slice(0, MAX_RESULTS)
  }

  // --- snippet ---------------------------------------------------------

  // Returns [{text, match}] segments, so the caller can build DOM nodes and
  // never has to hand-escape user input into innerHTML.
  function snippet(page, queryTerms) {
    var source = page.text || page.description
    if (!source) return null

    // normalize() collapses punctuation and so changes length; foldAligned()
    // keeps offsets usable against the original string.
    var aligned = foldAligned(source)

    var at = -1
    var hitTerm = ''
    for (var i = 0; i < queryTerms.length; i++) {
      var idx = aligned.indexOf(queryTerms[i])
      if (idx !== -1 && (at === -1 || idx < at)) {
        at = idx
        hitTerm = queryTerms[i]
      }
    }
    if (at === -1) {
      // Matched only on title/heading metadata; open with the page's own words.
      at = 0
      hitTerm = ''
    }

    var start = Math.max(0, at - SNIPPET_BEFORE)
    var end = Math.min(source.length, at + (hitTerm.length || 0) + SNIPPET_AFTER)

    // Avoid cutting mid-word at either edge.
    if (start > 0) {
      var space = source.indexOf(' ', start)
      if (space !== -1 && space < at) start = space + 1
    }
    if (end < source.length) {
      var lastSpace = source.lastIndexOf(' ', end)
      if (lastSpace > at) end = lastSpace
    }

    var excerpt = source.slice(start, end).trim()
    if (start > 0) excerpt = '… ' + excerpt
    if (end < source.length) excerpt = excerpt + ' …'

    return highlight(excerpt, queryTerms)
  }

  function highlight(text, queryTerms) {
    if (!queryTerms.length) return [{ text: text, match: false }]

    var pattern = queryTerms.map(escapeRe).sort(function (a, b) {
      return b.length - a.length
    }).join('|')
    var re = new RegExp('(' + pattern + ')', 'gi')

    var segments = []
    var last = 0
    var m
    while ((m = re.exec(text)) !== null) {
      if (m.index > last) segments.push({ text: text.slice(last, m.index), match: false })
      segments.push({ text: m[0], match: true })
      last = m.index + m[0].length
      if (m[0].length === 0) re.lastIndex++ // guard against a zero-width match
    }
    if (last < text.length) segments.push({ text: text.slice(last), match: false })
    return segments
  }

  // --- rendering -------------------------------------------------------

  function el(tag, className, text) {
    var node = document.createElement(tag)
    if (className) node.className = className
    if (text != null) node.textContent = text
    return node
  }

  function setStatus(message) {
    if (statusEl) statusEl.textContent = message
  }

  function clear(node) {
    while (node.firstChild) node.removeChild(node.firstChild)
  }

  function renderResults(hits, query) {
    clear(resultsEl)

    if (!hits.length) {
      setStatus('No results for “' + query + '”.')
      resultsEl.appendChild(
        el('p', 'description', 'No pages matched “' + query + '”. Try a different or more general term.')
      )
      return
    }

    setStatus(hits.length + (hits.length === 1 ? ' result' : ' results') + ' for “' + query + '”.')

    var list = el('div', 'search-result-list')
    var queryTerms = terms(query)

    for (var i = 0; i < hits.length; i++) {
      var page = hits[i].page
      var item = el('div', 'search-result-item')

      var link = el('a', 'search-header-link', page.title)
      link.href = page.url
      item.appendChild(link)

      item.appendChild(el('div', 'search-link', page.url))

      var segments = snippet(page, queryTerms)
      if (segments) {
        var p = el('p', 'description')
        for (var s = 0; s < segments.length; s++) {
          var seg = segments[s]
          p.appendChild(seg.match ? el('mark', null, seg.text) : document.createTextNode(seg.text))
        }
        item.appendChild(p)
      }

      list.appendChild(item)
    }

    resultsEl.appendChild(list)
  }

  function renderMessage(message) {
    clear(resultsEl)
    setStatus(message)
    resultsEl.appendChild(el('p', 'description', message))
  }

  // --- wiring ----------------------------------------------------------

  function loadIndex() {
    if (!indexPromise) {
      indexPromise = fetch(INDEX_URL, { credentials: 'same-origin' })
        .then(function (res) {
          if (!res.ok) throw new Error('HTTP ' + res.status)
          return res.json()
        })
        .then(prepare)
        .catch(function (err) {
          indexPromise = null // let a later submit retry rather than stay broken
          throw err
        })
    }
    return indexPromise
  }

  function currentQuery() {
    var params = new URLSearchParams(window.location.search)
    return (params.get('query') || params.get('q') || '').trim()
  }

  function run(query) {
    input.value = query

    if (!query) {
      clear(resultsEl)
      setStatus('')
      return
    }

    setStatus('Searching…')
    loadIndex().then(function (pages) {
      // Ignore a resolved index that a newer submit has already superseded.
      if (input.value.trim() !== query) return
      renderResults(search(pages, query), query)
    }).catch(function () {
      renderMessage('Search is temporarily unavailable. Please try again shortly.')
    })
  }

  form.addEventListener('submit', function (event) {
    var query = input.value.trim()

    // `required` accepts whitespace, so an all-spaces query would otherwise
    // submit and reload the page just to render nothing.
    if (!query) {
      event.preventDefault()
      input.value = ''
      clear(resultsEl)
      setStatus('')
      return
    }

    // Search in place, but keep the URL shareable and the back button working.
    if (window.history && window.history.pushState) {
      event.preventDefault()
      var url = window.location.pathname + '?query=' + encodeURIComponent(query)
      if (url !== window.location.pathname + window.location.search) {
        window.history.pushState({ query: query }, '', url)
      }
      run(query)
    }
    // Without pushState the form submits normally and the page re-renders.
  })

  window.addEventListener('popstate', function () {
    run(currentQuery())
  })

  // Warm the index while the visitor is still typing their first query.
  if (!currentQuery()) {
    input.addEventListener('focus', function () {
      loadIndex().catch(function () {})
    }, { once: true })
  }

  run(currentQuery())
})()
